#!/usr/bin/env bash
#
# Script name: quickshot
# Version: 1.0.0
# Description: A simple script to take screenshots with time stamps.
# Dependencies: maim, xclip, date, mkdir
# Github: https://github.com/Ninja-Yubaraj/Dotfiles
# Gitlab: https://gitlab.com/Ninja-Yubaraj/Dotfiles
# License: https://github.com/Ninja-Yubaraj/Dotfiles/LICENSE
# Contributors: Yubaraj Sarkar
# Code Status: Deprecated
# Reason: 1. Don't check for dependencies.
#         2. Don't check for the existence of the directory.
#         3. Don't notify the user.

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

path="$HOME/Pictures/Screenshots/$(date +'%Y-%m')"
#name="screenshot-$(date +'%Y-%m-%d-%H%M%S')-$(echo $USER)@$(echo $HOSTNAME).png"
name="screenshot-$(date +'%Y-%m-%d-%H%M%S').png"

mkdir -p $path
maim --select --capturebackground | tee $path/$name | xclip -selection clipboard -t image/png
